// #17 local wiki repo manager. The wiki proposed by a candidate (via gap-filling
// in #15) lands here on Promote. The repo is a plain on-disk git repo seeded from
// the bundled wiki/ at project root; commits are made via local git.
//
// The pre-commit lint check runs as a git pre-commit hook (a small shell script
// the manager writes at init time). Non-conforming pages fail the commit with a
// clear error and a list of issues from #16's linter. This means the linter is
// the load-bearing check, not the JS-side validation in `promote()` — the hook
// is the literal gate the issue calls for.
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import {
	chmod,
	copyFile,
	mkdir,
	readdir,
	readFile,
	rm,
	stat,
	writeFile,
} from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { existsSync } from "node:fs";

const execFileP = promisify(execFile);

export interface WikiRepoOptions {
	// On-disk root of the local repo (e.g. /data/wiki-repo). Created if missing.
	repoDir: string;
	// Where to copy seed pages from on first init (the project's wiki/ dir).
	seedDir: string;
	// Shell-safe command prefix the pre-commit hook invokes; the hook appends
	// the repo dir as the final arg. Examples:
	//   "node /app/server/dist/wiki/page_lint_cli.js"   (production)
	//   "npx tsx server/src/wiki/page_lint_cli.ts"      (dev / tests)
	// The repo dir is appended quoted, so this string doesn't need to handle
	// path escaping.
	linterCommand: string;
	// Commit identity (the candidate's email). Falls back to defaults if unset.
	authorEmail?: string;
	authorName?: string;
}

export interface PromoteInput {
	kind: "role" | "skill" | "industry";
	slug: string;
	markdown: string; // full page content including frontmatter
}

export interface PromoteResult {
	commit_sha: string;
	relative_path: string;
}

export class WikiPromoteError extends Error {
	constructor(
		message: string,
		public readonly stage: "lint" | "git" | "io",
		public readonly details?: string,
	) {
		super(message);
		this.name = "WikiPromoteError";
	}
}

const KIND_DIRS: Record<PromoteInput["kind"], string> = {
	role: "roles",
	skill: "skills",
	industry: "industries",
};

const PRE_COMMIT_HOOK = (linterCommand: string, repoDir: string) => `#!/bin/sh
# Auto-generated by Assay WikiRepo. Runs the #16 wiki linter against the local
# wiki repo before allowing the commit. Non-conforming pages fail the commit.
exec ${linterCommand} ${JSON.stringify(repoDir)}
`;

export class WikiRepo {
	constructor(private readonly opts: WikiRepoOptions) {}

	// Initialize the repo at opts.repoDir if it doesn't already exist. Seeds it
	// from opts.seedDir, configures a local user, installs the pre-commit hook,
	// and makes the baseline commit. Idempotent: a populated repo is left alone
	// except for the hook (which is rewritten in case the linter path changes).
	async initIfMissing(): Promise<void> {
		const gitDir = join(this.opts.repoDir, ".git");
		const alreadyAGitRepo = existsSync(gitDir);

		if (!alreadyAGitRepo) {
			await mkdir(this.opts.repoDir, { recursive: true });
			await this.git(["init", "--quiet", "--initial-branch=main"]);
			await this.git(["config", "user.email", this.opts.authorEmail ?? "wiki@assay.local"]);
			await this.git(["config", "user.name", this.opts.authorName ?? "Assay WikiRepo"]);
			await this.git(["config", "commit.gpgsign", "false"]);
			await this.copySeedPages();
		}

		await this.installPreCommitHook();

		if (!alreadyAGitRepo) {
			await this.git(["add", "."]);
			// Skip the hook on the initial seed commit — the seeds already passed
			// `npm run wiki:check` in CI and we don't want bootstrap to fail if a
			// seed page is briefly invalid in dev.
			await this.git(["commit", "--quiet", "--no-verify", "-m", "seed wiki from bundled pages"]);
		}
	}

	// Stage and commit a promoted page. The git pre-commit hook runs the linter
	// and rejects non-conforming content before the commit lands. On lint
	// failure, this method throws WikiPromoteError(stage="lint") with the
	// linter's stderr attached.
	async promote(input: PromoteInput): Promise<PromoteResult> {
		const dir = KIND_DIRS[input.kind];
		if (!dir) throw new WikiPromoteError(`unknown kind: ${input.kind}`, "io");
		const rel = `${dir}/${input.slug}.md`;
		const abs = join(this.opts.repoDir, rel);
		await mkdir(dirname(abs), { recursive: true });
		await writeFile(abs, input.markdown.endsWith("\n") ? input.markdown : input.markdown + "\n", "utf8");

		try {
			await this.git(["add", rel]);
		} catch (err) {
			throw new WikiPromoteError("git add failed", "git", errMessage(err));
		}

		try {
			await this.git(["commit", "-m", `promote ${input.slug}`]);
		} catch (err) {
			// The pre-commit hook prints to stderr; surface that to the caller.
			const detail = errMessage(err);
			// Roll back the staged change so the candidate can retry without
			// leftover state.
			await this.gitSafe(["restore", "--staged", rel]);
			await rm(abs, { force: true });
			const isLintFailure = /\berror\b|wiki-check/i.test(detail);
			throw new WikiPromoteError(
				isLintFailure ? "lint rejected proposal" : "git commit failed",
				isLintFailure ? "lint" : "git",
				detail,
			);
		}

		const { stdout } = await execFileP("git", ["rev-parse", "HEAD"], { cwd: this.opts.repoDir });
		return { commit_sha: stdout.trim(), relative_path: rel };
	}

	// Returns whether a slug exists in the repo (any kind directory). Used by
	// the gap-filling check to avoid re-proposing pages that already exist.
	async hasPage(slug: string): Promise<boolean> {
		for (const dir of Object.values(KIND_DIRS)) {
			if (existsSync(join(this.opts.repoDir, dir, `${slug}.md`))) return true;
		}
		return false;
	}

	// ---------------- internals ----------------

	private async copySeedPages(): Promise<void> {
		// Copy wiki/{roles,skills,industries}/*.md plus README.md from seedDir.
		for (const entry of ["README.md", ...Object.values(KIND_DIRS)]) {
			const src = join(this.opts.seedDir, entry);
			const dst = join(this.opts.repoDir, entry);
			let s: Awaited<ReturnType<typeof stat>>;
			try {
				s = await stat(src);
			} catch {
				continue;
			}
			if (s.isDirectory()) {
				await mkdir(dst, { recursive: true });
				const names = await readdir(src);
				for (const n of names) {
					if (n.endsWith(".md")) await copyFile(join(src, n), join(dst, n));
				}
			} else {
				await mkdir(dirname(dst), { recursive: true });
				await copyFile(src, dst);
			}
		}
	}

	private async installPreCommitHook(): Promise<void> {
		const hookPath = join(this.opts.repoDir, ".git", "hooks", "pre-commit");
		await mkdir(dirname(hookPath), { recursive: true });
		await writeFile(hookPath, PRE_COMMIT_HOOK(this.opts.linterCommand, resolve(this.opts.repoDir)), "utf8");
		await chmod(hookPath, 0o755);
	}

	private async git(args: string[]): Promise<{ stdout: string; stderr: string }> {
		try {
			const r = await execFileP("git", args, { cwd: this.opts.repoDir });
			return { stdout: r.stdout, stderr: r.stderr };
		} catch (err) {
			// execFile rejects with an error that has stdout/stderr attached when
			// the command exits non-zero. We rethrow with a string that includes
			// both streams so callers can distinguish lint vs. git failure.
			const e = err as { stdout?: string; stderr?: string; message?: string };
			const detail = [e.stderr, e.stdout, e.message].filter(Boolean).join("\n").trim();
			throw new Error(detail || "git command failed");
		}
	}

	private async gitSafe(args: string[]): Promise<void> {
		try {
			await this.git(args);
		} catch {
			// best-effort cleanup; ignore failures
		}
	}
}

function errMessage(err: unknown): string {
	if (err instanceof Error) return err.message;
	return String(err);
}

// Helper consumed by tests that want a tmp dir setup. Not strictly part of the
// production API; exported so the integration test in wiki-proposals can reuse
// the same plumbing.
export async function readWikiFile(repoDir: string, relativePath: string): Promise<string | null> {
	try {
		return await readFile(join(repoDir, relativePath), "utf8");
	} catch {
		return null;
	}
}
